### ISSUE TITLE
Issue running, Index out of range.

### ISSUE THREAD

**Issue by dwebber1** [echo-oddly/gsioc_controller#1]
Hi, I am trying to run a buffered command, and when I call my python script I get this:

line 78 in bCommand
readySig = s.read(0)[1]
indexError: index out of range

any ideas?

**Comment by drvirgilio** [comment]
It should be `s.read(1)[0]`
This tells pySerial to read 1 byte from the serial device into an array and return the zeroth byte in the array.

**Comment by dwebber1** [comment]
Okay, thank you. When writing, and testing this software did you connect directly to the device or were you using a system interface module like the 506C?

**Comment by drvirgilio** [comment]
I don't remember exactly but I think I connected through some sort of interface which connected to multiple devices.
